pull_request_rules:
  - name: automatic merge when GitHub branch protection passes
    conditions:
      - base=master
      - 'label=:shipit: merge'
    actions:
      merge:
        method: squash
        strict: smart
  - name: automatic merge when GitHub branch protection passes and delete head branch after merge
    conditions:
      - merged
      - 'label=:shipit: merge'
    actions:
      label:
        remove:
          - ':shipit: merge'
      delete_head_branch: {}
