name: Update Milestone

on:
  workflow_call:
    # inputs:
    secrets:
      GITHUB_TOKEN:
        type: string
        required: true

jobs:
  update_milestone:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2.4.0

      - name: sync milestones
        uses: RocketSurgeonsGuild/actions/sync-milestone@v0.2.4
        with:
          default-label: ':sparkles: mysterious'
          github-token: ${{ secrets.GITHUB_TOKEN }}
