name: Sync Labels

on:
  workflow_call:
    # inputs:
    secrets:
      GITHUB_TOKEN:
        type: string
        required: true

jobs:
  sync_labels:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2.4.0

      - name: Checkout tools repo
        uses: actions/checkout@v2.4.0
        with:
          repository: RocketSurgeonsGuild/.github
          path: .rsg

      - name: merge files
        uses: RocketSurgeonsGuild/actions/merge-labels@v0.2.4
        with:
          files: '.rsg/.github/labels.yml,.github/labels.yml'
          output: .github/labels.yml

      - name: Run Labeler
        if: success()
        uses: crazy-max/ghaction-github-labeler@v3.1.1
        with:
          yaml_file: .github/labels.yml
          skip_delete: false
          dry_run: false
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
