name: 'Auto Label'
description: 'Automatically labels a PR based on some prefix in the title.'
inputs:
  github-token:
    description: 'Token for the repository. Can be passed in using {{ secrets.GITHUB_TOKEN }}'
    required: true
runs:
  using: 'node12'
  main: 'dist/index.js'
