name: Close Milestone
on:
  release:
    types:
      - released
jobs:
  milestone:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Install GitVersion
        uses: gittools/actions/gitversion/setup@master
        with:
          versionSpec: '5.x'

      - name: Use GitVersion
        id: gitversion
        uses: gittools/actions/gitversion/execute@master

      # Ensure the milestone exists
      - name: Create Milestone
        uses: WyriHaximus/github-action-create-milestone@0.1.0
        with:
          title: v${{ steps.gitversion.outputs.majorMinorPatch }}
        env:
          GITHUB_TOKEN: '${{ secrets.GITHUB_TOKEN }}'
        continue-on-error: true

      # move any issues to that milestone in the event the release is renamed
      - name: sync milestones
        uses: ./sync-milestone/
        with:
          default-label: ':sparkles: mysterious'
          github-token: ${{ secrets.GITHUB_TOKEN }}

      - name: Close Milestone
        uses: adlerhsieh/prepare-release@0.1.1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          REPO_OWNER: ''
          REPO: ''
