name: Close Milestone

on:
  release:
    types:
      - released

jobs:
  close_milestone:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2.3.4
        with:
          fetch-depth: 0

      - name: Install GitReleaseManager
        uses: gittools/actions/gitreleasemanager/setup@v0.9.10
        with:
          versionSpec: '0.11.x'

      # Ensure the milestone exists
      - name: Create Milestone
        uses: WyriHaximus/github-action-create-milestone@v1
        with:
          title: ${{ github.event.release.name }}
        env:
          GITHUB_TOKEN: '${{ secrets.GITHUB_TOKEN }}'
        continue-on-error: true

      # move any issues to that milestone in the event the release is renamed
      - name: sync milestones
        uses: ./sync-milestone/
        with:
          default-label: ':sparkles: mysterious'
          github-token: ${{ secrets.RSG_BOT_TOKEN }}

      # Close the milestone based on the given release
      - name: Close Milestone
        shell: pwsh
        if: ${{ !github.event.release.prerelease }}
        run: |
          dotnet gitreleasemanager close `
            -o "${{ github.event.repository.owner.login }}" `
            -r "${{ github.event.repository.name }}" `
            --token "${{ secrets.GITHUB_TOKEN }}" `
            -m "${{ github.event.release.name }}"
