name: Close Milestone

on:
  workflow_call:
    # inputs:
    secrets:
      RSG_BOT_TOKEN:
        required: true
  release:
    types:
      - released

jobs:
  close_milestone:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@d632683dd7b4114ad314bca15554477dd762a938 # v4.2.0
        with:
          fetch-depth: 0

      - name: 🔨 Use .NET Core 3.1 SDK
        uses: actions/setup-dotnet@v4.0.1
        with:
          dotnet-version: '3.1.x'

      - name: Install GitVersion
        uses: gittools/actions/gitversion/setup@v3.0.0
        with:
          versionSpec: '5.x'

      - name: Install GitReleaseManager
        uses: gittools/actions/gitreleasemanager/setup@v3.0.0
        with:
          versionSpec: '0.16.x'

      - name: Use GitVersion
        id: gitversion
        uses: gittools/actions/gitversion/execute@v3.0.0

      # Ensure the milestone exists
      - name: Create Milestone
        uses: WyriHaximus/github-action-create-milestone@v1
        with:
          title: v${{ steps.gitversion.outputs.majorMinorPatch }}
        env:
          GITHUB_TOKEN: '${{ secrets.GITHUB_TOKEN }}'
        continue-on-error: true

      # move any issues to that milestone in the event the release is renamed
      - name: sync milestones
        uses: RocketSurgeonsGuild/actions/sync-milestone@v0.3.11
        with:
          default-label: ':sparkles: mysterious'
          github-token: ${{ secrets.RSG_BOT_TOKEN }}

      - name: Get Repo and Owner
        shell: pwsh
        id: repository
        if: ${{ !github.event.release.prerelease && steps.gitversion.outputs.preReleaseTag == '' }}
        run: |
          $parts = $ENV:GITHUB_REPOSITORY.Split('/')
          echo "::set-output name=owner::$($parts[0])"
          echo "::set-output name=repository::$($parts[1])"

      - name: Close Milestone
        shell: pwsh
        if: ${{ !github.event.release.prerelease && steps.gitversion.outputs.preReleaseTag == '' }}
        run: |
          dotnet gitreleasemanager close `
            -o "${{ steps.repository.outputs.owner }}" `
            -r "${{ steps.repository.outputs.repository }}" `
            --token "${{ secrets.GITHUB_TOKEN }}" `
            -m "v${{ steps.gitversion.outputs.majorMinorPatch }}"
