name: Create Milestone
on:
  push:
    branches:
      - master
jobs:
  milestone:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Fetch all history for all tags and branches
        run: git fetch --prune --unshallow
      - name: Install GitVersion
        uses: gittools/actions/gitversion/setup@master
        with:
          versionSpec: '5.x'
      - name: Use GitVersion
        id: gitversion
        uses: gittools/actions/gitversion/execute@master
      - name: Install GitReleaseManager
        uses: gittools/actions/gitreleasemanager/setup@master
        with:
          versionSpec: '0.11.x'
      - name: Create Milestone
        uses: WyriHaximus/github-action-create-milestone@0.1.0
        with:
          title: v${{ steps.gitversion.outputs.majorMinorPatch }}
        env:
          GITHUB_TOKEN: '${{ secrets.GITHUB_TOKEN }}'
        continue-on-error: true

      - name: sync milestones
        uses: ./sync-milestone/
        with:
          default-label: ':sparkles: mysterious'
          github-token: ${{ secrets.GITHUB_TOKEN }}
