name: Dependabot Commenter

on:
  workflow_call:
    # inputs:
    secrets:
      RSG_BOT_TOKEN:
        required: true
  pull_request_target:
    types:
      - labeled
      - opened
      - reopened
      - closed

jobs:
  batch-update:
    runs-on: ubuntu-latest
    if: |
      (github.event.action == 'opened' || github.event.action == 'reopened') &&
      (github.event.pull_request.user.login == 'dependabot[bot]' || github.event.pull_request.user.login == 'dependabot-preview[bot]') &&
      contains(github.event.pull_request.labels.*.name, '.NET')
    steps:
      - name: Dump GitHub context
        env:
          GITHUB_CONTEXT: ${{ toJson(github) }}
        run: echo "$GITHUB_CONTEXT"

      - name: Dump job context
        env:
          JOB_CONTEXT: ${{ toJson(job) }}
        run: echo "$JOB_CONTEXT"

      - name: Dump steps context
        env:
          STEPS_CONTEXT: ${{ toJson(steps) }}
        run: echo "$STEPS_CONTEXT"

      - name: Dump runner context
        env:
          RUNNER_CONTEXT: ${{ toJson(runner) }}
        run: echo "$RUNNER_CONTEXT"

      - uses: actions/checkout@v2.4.0
        with:
          ref: ${{ github.head_ref }}
          token: ${{ secrets.RSG_BOT_TOKEN }}

      - run: dotnet tool install -g nukeeper

      - name: Run nukeeper
        uses: nick-invision/retry@v2
        with:
          timeout_seconds: 30
          max_attempts: 1
          continue_on_error: true
          shell: pwsh
          command: |
            $title = '${{ github.event.pull_request.title }}'
            $prefix = '';
            if ($title.StartsWith('Bump Rocket.Surgery'))
            {
              $prefix = ($title.Split(' ')[1].Split('.') | select -First 3) -join '.'
            }
            elseif ($title.StartsWith('Bump Microsoft'))
            {
              $prefix = ($title.Split(' ')[1].Split('.') | select -First 2) -join '.'
            }
            elseif ($title.StartsWith('Bump Nuke') -or $title.StartsWith('Bump Rocket.Surgery.Nuke'))
            {
              $prefix = 'Nuke'
            }
            else
            {
              $prefix = ($title.Split(' ')[1].Split('.') | select -First 1) -join '.'
            }
            if ($prefix)
            {
              nukeeper update -m 100 -i "$prefix" -a 0
            }

      - uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: Update packages in a batch
          file_pattern: '*.props *.targets *.*proj'
          push_options: '--force'
  comment:
    runs-on: ubuntu-latest
    steps:
      - name: Dump GitHub context
        env:
          GITHUB_CONTEXT: ${{ toJson(github) }}
        run: echo "$GITHUB_CONTEXT"

      - name: Dump job context
        env:
          JOB_CONTEXT: ${{ toJson(job) }}
        run: echo "$JOB_CONTEXT"

      - name: Dump steps context
        env:
          STEPS_CONTEXT: ${{ toJson(steps) }}
        run: echo "$STEPS_CONTEXT"

      - name: Dump runner context
        env:
          RUNNER_CONTEXT: ${{ toJson(runner) }}
        run: echo "$RUNNER_CONTEXT"

      - uses: actions/checkout@v2.4.0
        with:
          ref: master

      - name: Dependabot Commenter
        uses: actions-ecosystem/action-create-comment@v1
        if: |
          (github.event.action == 'labeled' || github.event.action == 'opened' || github.event.action == 'reopened')
          && (github.event.pull_request.user.login == 'dependabot[bot]' || github.event.pull_request.user.login == 'dependabot-preview[bot]')
          && (
              contains(github.event.pull_request.labels.*.name, ':shipit: merge')
           || contains(github.event.pull_request.labels.*.name, 'javascript')
           || contains(github.event.pull_request.labels.*.name, 'github-actions')
          )
        with:
          github_token: '${{ secrets.RSG_BOT_TOKEN }}'
          body: '@dependabot squash and merge'

      - name: GitHub Automerge
        if: |
          (
            github.event.label.name == ':shipit: merge'
          ) && (
               github.event.pull_request.user.login != 'dependabot[bot]'
            && github.event.pull_request.user.login != 'dependabot-preview[bot]'
          )
        uses: alexwilson/enable-github-automerge-action@1.0.0
        with:
          github-token: '${{ secrets.GITHUB_TOKEN }}'
          merge-method: 'SQUASH'

      - name: GitHub Add Labels
        uses: actions-ecosystem/action-add-labels@v1
        if: |
             (github.event.action == 'opened' || github.event.action == 'reopened') &&
             (github.event.pull_request.user.login == 'dependabot[bot]' || github.event.pull_request.user.login == 'dependabot-preview[bot]') &&
             (
                  startsWith(github.event.pull_request.title, 'Bump JetBrains.ReSharper.CommandLineTools')
               || startsWith(github.event.pull_request.title, 'Bump ReportGenerator')
               || startsWith(github.event.pull_request.title, 'Bump Nuke.Common')
               || startsWith(github.event.pull_request.title, 'Bump GitVersion.Tool')
               || startsWith(github.event.pull_request.title, 'Bump Bogus')
               || startsWith(github.event.pull_request.title, 'Bump coverlet')
               || startsWith(github.event.pull_request.title, 'Bump FakeItEasy')
               || startsWith(github.event.pull_request.title, 'Bump FluentAssertions')
               || startsWith(github.event.pull_request.title, 'Bump xunit')
               || startsWith(github.event.pull_request.title, 'Bump Microsoft.NET.Test.Sdk')
               || startsWith(github.event.pull_request.title, 'Bump Microsoft.SourceLink')
               || startsWith(github.event.pull_request.title, 'Bump Microsoft.Extensions')
               || startsWith(github.event.pull_request.title, 'Bump Microsoft.AspNetCore')
               || startsWith(github.event.pull_request.title, 'Bump Rocket.Surgery.Nuke')
               || startsWith(github.event.pull_request.title, 'Bump Rocket.Surgery.MSBuild')
               || startsWith(github.event.pull_request.title, 'Bump Roslynator.Analyzers')
             )
        with:
          labels: |
            :shipit: merge

      - name: GitHub Remove Labels
        if: |
          github.event.action == 'closed' && github.event.pull_request.merged == 'true'
        uses: actions-ecosystem/action-remove-labels@v1
        with:
          labels: |
            :shipit: merge
            github-actions
            javascript
            .NET
