name: Dependabot Commenter

on:
  workflow_call:
    # inputs:
    secrets:
      RSG_BOT_TOKEN:
        required: true
  pull_request_target:
    types:
      - labeled
      - opened
      - reopened
      - closed
      - synchronize
      - ready_for_review

jobs:
  comment:
    runs-on: ubuntu-latest
    if: |
      (github.event.action != 'closed')
    steps:
      - name: Dump GitHub context
        env:
          GITHUB_CONTEXT: ${{ toJson(github) }}
        run: echo "$GITHUB_CONTEXT"

      - name: Dump job context
        env:
          JOB_CONTEXT: ${{ toJson(job) }}
        run: echo "$JOB_CONTEXT"

      - name: Dump steps context
        env:
          STEPS_CONTEXT: ${{ toJson(steps) }}
        run: echo "$STEPS_CONTEXT"

      - name: Dump runner context
        env:
          RUNNER_CONTEXT: ${{ toJson(runner) }}
        run: echo "$RUNNER_CONTEXT"

      - name: GitHub Automerge
        if: |
          contains(github.event.pull_request.labels.*.name, ':shipit: merge')
        uses: alexwilson/enable-github-automerge-action@2.0.0
        continue-on-error: true
        with:
          github-token: '${{ secrets.RSG_BOT_TOKEN }}'
          merge-method: 'SQUASH'

  labeler:
    runs-on: ubuntu-latest
    if: |
      (github.event.action != 'labeled')
    steps:
      - name: Dump GitHub context
        env:
          GITHUB_CONTEXT: ${{ toJson(github) }}
        run: echo "$GITHUB_CONTEXT"

      - name: Dump job context
        env:
          JOB_CONTEXT: ${{ toJson(job) }}
        run: echo "$JOB_CONTEXT"

      - name: Dump steps context
        env:
          STEPS_CONTEXT: ${{ toJson(steps) }}
        run: echo "$STEPS_CONTEXT"

      - name: Dump runner context
        env:
          RUNNER_CONTEXT: ${{ toJson(runner) }}
        run: echo "$RUNNER_CONTEXT"

      - name: GitHub Private Dependency Labels
        if: |
          (github.event.action != 'closed') &&
          (github.event.pull_request.user.login == 'renovate[bot]' && contains(github.event.pull_request.labels.*.name, ':truck: private-dependencies'))
        uses: actions-ecosystem/action-add-labels@v1
        with:
          labels: |
            :shipit: merge

      - name: GitHub Remove Labels
        if: |
          github.event.action == 'closed'
        uses: actions-ecosystem/action-remove-labels@v1
        with:
          labels: |
            :shipit: merge
