name: Update Milestone
on:
  pull_request_target:
    types:
      - closed
      - opened
      - reopened
      - synchronize

jobs:
  update_milestone:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2.3.4
        with:
          fetch-depth: 0

      - name: Fetch all history for all tags and branches
        run: git fetch --prune

      - name: Install GitVersion
        if: ${{ github.event.action == 'opened' }}
        uses: gittools/actions/gitversion/setup@v0.9.11
        with:
          versionSpec: '5.x'

      - name: Install GitReleaseManager
        if: ${{ github.event.action == 'opened' }}
        uses: gittools/actions/gitreleasemanager/setup@v0.9.11
        with:
          versionSpec: '0.11.x'

      - name: Use GitVersion
        if: ${{ github.event.action == 'opened' }}
        id: gitversion
        uses: gittools/actions/gitversion/execute@v0.9.11

      - name: Create Milestone
        if: ${{ github.event.action == 'opened' }}
        uses: WyriHaximus/github-action-create-milestone@v1
        with:
          title: v${{ steps.gitversion.outputs.majorMinorPatch }}
        env:
          GITHUB_TOKEN: '${{ secrets.GITHUB_TOKEN }}'
        continue-on-error: true

      - name: sync milestones
        uses: ./sync-milestone/
        with:
          default-label: ':sparkles: mysterious'
          github-token: ${{ secrets.GITHUB_TOKEN }}
