name: Update Milestone

on:
  workflow_call:
  pull_request_target:
    types:
      - closed
      - opened
      - reopened
      - synchronize

jobs:
  update_milestone:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
        with:
          ref: ${{ github.sha }}
          fetch-depth: 0

      - name: Fetch all history for all tags and branches
        run: git fetch --prune

      - uses: actions/setup-dotnet@v4

      - name: Install GitVersion
        if: ${{ github.event.action == 'opened' }}
        uses: gittools/actions/gitversion/setup@v4.1.0
        with:
          # renovate: datasource=github-releases depName=gittools/gitversion
          versionSpec: '6.1.0'

      - name: Install GitReleaseManager
        if: ${{ github.event.action == 'opened' }}
        uses: gittools/actions/gitreleasemanager/setup@v4.1.0
        with:
          # renovate: datasource=github-releases depName=gittools/gitreleasemanager
          versionSpec: '0.18.0'

      - name: Use GitVersion
        if: ${{ github.event.action == 'opened' }}
        id: gitversion
        uses: gittools/actions/gitversion/execute@v4.1.0

      - name: Create Milestone
        if: ${{ github.event.action == 'opened' }}
        uses: WyriHaximus/github-action-create-milestone@v1
        with:
          title: v${{ steps.gitversion.outputs.majorMinorPatch }}
        env:
          GITHUB_TOKEN: '${{ secrets.GITHUB_TOKEN }}'
        continue-on-error: true

      - name: sync milestones
        uses: RocketSurgeonsGuild/actions/sync-milestone@v0.3.15
        with:
          default-label: ':sparkles: mysterious'
          github-token: ${{ secrets.GITHUB_TOKEN }}
